name: Zapier Release

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Install Zapier CLI
        run: npm install -g zapier-platform-cli

      - name: Create Zapier config
        env:
          ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
        run: |
          echo "{\"id\":${{ secrets.ZAPIER_INTEGRATION_ID }}, \"key\":\"${{ secrets.ZAPIER_DEPLOY_KEY }}\"}" > .zapierapprc

      - name: Deploy to Zapier
        env:
          ZAPIER_DEPLOY_KEY: ${{ secrets.ZAPIER_DEPLOY_KEY }}
        run: zapier push --skip-npm-install
